name: YamDB Workflow

on: [push]

jobs:
  tests:
    runs on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pep8-naming flake8-broken-line flake8-returns flake8-isort
          pip install -r requirements.txt
      
      - name: Test with Flake8 and Django test
        run: |
          python -m flake8
          python manage.py test
  build_and_push_to_docker:
  deploy:
  send_message: